#include <Arduino.h>
#include "esp_camera.h"
#include <hazard_beacon_inferencing.h>  // Edge Impulse generated library (model + inference SDK)
#include "esp_task_wdt.h"               // Watchdog timer — used to prevent reset during long inference

#include "test_image.h"  // generated by scripts/image_to_header.py

// Telegram/WiFi includes — uncomment when re-enabling remote alerts
// #include <WiFi.h>
// #include <WiFiClientSecure.h>
// #include <HTTPClient.h>
// #include <ArduinoJson.h>
// #include "credentials.h"

// ── Camera pin definitions ────────────────────────────────────────────────────
// The ESP32-S3-EYE has different camera wiring than the board variant defaults,
// so we clear the defaults first and set the correct GPIO numbers for this board.
#undef PWDN_GPIO_NUM
#undef RESET_GPIO_NUM
#undef XCLK_GPIO_NUM
#undef SIOD_GPIO_NUM
#undef SIOC_GPIO_NUM
#undef Y9_GPIO_NUM
#undef Y8_GPIO_NUM
#undef Y7_GPIO_NUM
#undef Y6_GPIO_NUM
#undef Y5_GPIO_NUM
#undef Y4_GPIO_NUM
#undef Y3_GPIO_NUM
#undef Y2_GPIO_NUM
#undef VSYNC_GPIO_NUM
#undef HREF_GPIO_NUM
#undef PCLK_GPIO_NUM

#define PWDN_GPIO_NUM  -1  // Power down — not used on this board
#define RESET_GPIO_NUM -1  // Hardware reset — not used on this board
#define XCLK_GPIO_NUM  15  // Clock signal fed into the camera sensor
#define SIOD_GPIO_NUM  4   // SCCB data pin (camera's I2C-like config bus)
#define SIOC_GPIO_NUM  5   // SCCB clock pin
#define Y9_GPIO_NUM    16  // Pixel data bus MSB
#define Y8_GPIO_NUM    17
#define Y7_GPIO_NUM    18
#define Y6_GPIO_NUM    12
#define Y5_GPIO_NUM    10
#define Y4_GPIO_NUM    8
#define Y3_GPIO_NUM    9
#define Y2_GPIO_NUM    11  // Pixel data bus LSB
#define VSYNC_GPIO_NUM 6   // Pulses once per complete frame
#define HREF_GPIO_NUM  7   // Pulses once per row of pixels
#define PCLK_GPIO_NUM  13  // Pixel clock — pulses once per pixel

#define LED_PIN        21  // Yellow alert LED — set HIGH when a hazard is detected

// Debug: when 1, each classified frame is streamed over serial so
// scripts/capture_classified_frames.py can save the exact bitmap the model saw.
// Set to 0 for normal deployment (it adds ~0.8s/frame of serial transfer).
#define DUMP_FRAMES    1

// ── Shared frame buffer pointer ───────────────────────────────────────────────
// loop() sets this to point at the camera frame. The Edge Impulse signal
// callback (get_signal_data) reads from it to feed pixels into the classifier.
static uint8_t *frame_buf_ptr = nullptr;

// ── Telegram alert (disabled) ─────────────────────────────────────────────────
// Sends a Telegram message when a hazard is detected. Requires WiFi credentials
// in credentials.h and the WiFi/HTTP includes above.
/*
static const uint32_t ALERT_COOLDOWN_MS = 30000;  // minimum ms between alerts
static uint32_t last_alert_ms = 0;

static void sendTelegramAlert(float score) {
    if (WiFi.status() != WL_CONNECTED) return;
    WiFiClientSecure client;
    client.setInsecure();
    HTTPClient https;
    String url = String("https://api.telegram.org/bot") + TELEGRAM_BOT_TOKEN + "/sendMessage";
    if (!https.begin(client, url)) return;
    https.addHeader("Content-Type", "application/json");
    JsonDocument doc;
    doc["chat_id"] = TELEGRAM_CHAT_ID;
    doc["text"]    = String("Hazard detected! Confidence: ") + String(score * 100, 0) + "%";
    String body;
    serializeJson(doc, body);
    int code = https.POST(body);
    Serial.printf("[Telegram] response code: %d\n", code);
    https.end();
}
*/

// ── Edge Impulse signal callback ──────────────────────────────────────────────
// Edge Impulse doesn't read the image directly — it calls this function to
// pull pixel data in chunks. We convert each raw byte (0–255) to a float
// (0.0–1.0) because that's the format the model was trained on.
static int get_signal_data(size_t offset, size_t length, float *out_ptr) {
    for (size_t i = 0; i < length; i++) {
        uint8_t gray = frame_buf_ptr[offset + i];
        // EI image DSP block is configured for RGB — pack grayscale as R=G=B
        out_ptr[i] = (float)((gray << 16) | (gray << 8) | gray);
    }
    return EIDSP_OK;
}

// ── Setup — runs once on boot ─────────────────────────────────────────────────
void setup() {
    // Start serial at 115200 baud for debug output in the serial monitor
    Serial.begin(115200);

    // Wait up to 5 seconds for a USB serial connection before continuing
    uint32_t t = millis();
    while (!Serial && (millis() - t) < 5000) delay(10);
    delay(1000);

    // Set up the alert LED — starts OFF
    pinMode(LED_PIN, OUTPUT);
    digitalWrite(LED_PIN, LOW);

    Serial.println("=== Hazard Beacon - Inference Mode ===");
    Serial.printf("PSRAM total: %u bytes  free: %u bytes\n",
                  ESP.getPsramSize(), ESP.getFreePsram());

    // ── WiFi (disabled) ───────────────────────────────────────────────────────
    // Uncomment to connect to WiFi and enable Telegram alerts.
    /*
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    Serial.print("Connecting to WiFi");
    uint32_t wifi_start = millis();
    while (WiFi.status() != WL_CONNECTED && (millis() - wifi_start) < 15000) {
        delay(500);
        Serial.print(".");
    }
    if (WiFi.status() == WL_CONNECTED) {
        Serial.printf("\nWiFi connected: %s\n", WiFi.localIP().toString().c_str());
    } else {
        Serial.println("\nWiFi failed — continuing without notifications");
    }
    */

    // ── Camera initialisation ─────────────────────────────────────────────────
    // Configure the OV2640 camera sensor. The resolution (96×96) and pixel
    // format (grayscale) must match what the model was trained on in Edge Impulse.
    camera_config_t config;
    config.ledc_channel = LEDC_CHANNEL_0;      // LEDC peripheral generates the XCLK signal
    config.ledc_timer   = LEDC_TIMER_0;
    config.pin_d0       = Y2_GPIO_NUM;         // 8-bit parallel pixel data bus
    config.pin_d1       = Y3_GPIO_NUM;
    config.pin_d2       = Y4_GPIO_NUM;
    config.pin_d3       = Y5_GPIO_NUM;
    config.pin_d4       = Y6_GPIO_NUM;
    config.pin_d5       = Y7_GPIO_NUM;
    config.pin_d6       = Y8_GPIO_NUM;
    config.pin_d7       = Y9_GPIO_NUM;
    config.pin_xclk     = XCLK_GPIO_NUM;
    config.pin_pclk     = PCLK_GPIO_NUM;
    config.pin_vsync    = VSYNC_GPIO_NUM;
    config.pin_href     = HREF_GPIO_NUM;
    config.pin_sccb_sda = SIOD_GPIO_NUM;
    config.pin_sccb_scl = SIOC_GPIO_NUM;
    config.pin_pwdn     = PWDN_GPIO_NUM;
    config.pin_reset    = RESET_GPIO_NUM;
    config.xclk_freq_hz = 20000000;            // 20 MHz clock to the sensor
    config.pixel_format = PIXFORMAT_GRAYSCALE; // Single channel — matches training data
    config.frame_size   = FRAMESIZE_96X96;     // 96×96 pixels — must match model input size
    config.fb_count     = 2;                   // Two frame buffers so capture and inference can overlap
    config.grab_mode    = CAMERA_GRAB_LATEST;  // Always grab the most recent frame (discard stale ones)

    esp_err_t err = esp_camera_init(&config);
    if (err != ESP_OK) {
        Serial.printf("Camera init FAILED: 0x%x\n", err);
        return;
    }

    // ── Lock exposure / gain (fixed Ring-style scene) ─────────────────────────
    // Sensor settings must be applied AFTER esp_camera_init(). We lock exposure and
    // gain so the background looks identical every frame. This prevents the model
    // from keying on brightness: with auto-exposure ON and a white background, an
    // intruder lowers average brightness, the sensor raises exposure, and background
    // brightness becomes correlated with the class. Locking removes that confound and
    // also stops the dark/bright frame flip. Tune AEC_VALUE once so the empty scene is
    // well-exposed (not clipped white); the same value is used for collect and deploy.
    sensor_t *s = esp_camera_sensor_get();
    if (s) {
        const int AEC_VALUE = 300;      // fixed exposure — tune to your scene/lighting
        const int AGC_GAIN  = 0;        // fixed gain (0 = lowest)
        s->set_exposure_ctrl(s, 0);     // disable auto exposure (AEC)
        s->set_aec2(s, 0);              // disable AEC2 algorithm
        s->set_aec_value(s, AEC_VALUE); // apply fixed exposure
        s->set_gain_ctrl(s, 0);         // disable auto gain (AGC)
        s->set_agc_gain(s, AGC_GAIN);   // apply fixed gain
        s->set_whitebal(s, 0);          // disable auto white-balance drift
        // For nighttime IR later: raise AEC_VALUE / AGC_GAIN and set GAINCEILING_16X.
    }

    Serial.println("Camera initialized (exposure locked). Running inference every 2 seconds...");
}

/*
// ── TEST MODE loop (disabled) ─────────────────────────────────────────────────
// Instead of using the camera, this loop receives images over USB serial from
// scripts/test_exported_model.py and runs the classifier on them. Used to
// validate model accuracy against labelled images without needing a live scene.
// Swap the comments to re-enable test mode.
void loop() {
    static uint8_t test_img_buf[EI_CLASSIFIER_INPUT_WIDTH * EI_CLASSIFIER_INPUT_HEIGHT];
    const size_t img_size = EI_CLASSIFIER_INPUT_WIDTH * EI_CLASSIFIER_INPUT_HEIGHT;

    // Announce readiness every 2 seconds so the Python script knows when to start
    static uint32_t last_ready_ms = 0;
    if (!Serial.available()) {
        if (millis() - last_ready_ms > 2000) {
            Serial.println("TEST_MODE_READY");
            last_ready_ms = millis();
        }
        return;
    }

    // Read the header: TEST_IMAGE:<true_label>:<num_bytes>
    String header = Serial.readStringUntil('\n');
    header.trim();
    if (!header.startsWith("TEST_IMAGE:")) return;

    int last_colon = header.lastIndexOf(':');
    size_t num_bytes = header.substring(last_colon + 1).toInt();

    if (num_bytes != img_size) {
        Serial.printf("RESULT:error:bad_size_%u\n", num_bytes);
        return;
    }

    // ACK the header so Python starts sending image bytes
    Serial.println("HEADER_OK");

    // Receive image in 64-byte chunks, ACKing each one before the next arrives
    const size_t CHUNK = 64;
    size_t received = 0;
    while (received < num_bytes) {
        size_t want = min(CHUNK, num_bytes - received);
        size_t got  = Serial.readBytes(test_img_buf + received, want);
        if (got != want) {
            Serial.printf("RESULT:error:timeout_%u\n", received + got);
            return;
        }
        received += got;
        Serial.println("ACK");
    }

    // Run inference on the received image
    frame_buf_ptr = test_img_buf;
    signal_t signal;
    signal.total_length = img_size;
    signal.get_data     = &get_signal_data;

    ei_impulse_result_t result = { 0 };
    esp_task_wdt_reset();
    EI_IMPULSE_ERROR ei_err = run_classifier(&signal, &result, false);

    if (ei_err != EI_IMPULSE_OK) {
        Serial.printf("RESULT:error:%d\n", ei_err);
        return;
    }

    // Find the highest-scoring class and send it back
    const char *best_label = "";
    float best_score = 0.0f;
    for (size_t i = 0; i < EI_CLASSIFIER_LABEL_COUNT; i++) {
        if (result.classification[i].value > best_score) {
            best_score = result.classification[i].value;
            best_label = result.classification[i].label;
        }
    }
    Serial.printf("RESULT:%s:%.4f\n", best_label, best_score);
}
*/

// ── NORMAL CAMERA MODE loop ───────────────────────────────────────────────────
// Runs continuously. Each iteration: captures a frame, runs the classifier,
// lights the LED if a hazard is detected, and prints the result to serial.
void loop() {
    // Step 1: Capture a frame from the camera into a DMA buffer
    camera_fb_t *fb = esp_camera_fb_get();
    if (!fb) {
        Serial.println("ERROR: Frame capture failed");
        delay(1000);
        return;
    }

    // Step 2: Point the global frame pointer at the captured pixel data
    frame_buf_ptr = fb->buf;

    // ── Test image mode (disabled) ────────────────────────────────────────────
    // Uncomment to skip the camera and cycle through hardcoded test images instead.
    // Run scripts/image_to_header.py first to generate test_image.h, then comment
    // out the camera block above and uncomment below.
    // static int img_idx = 0;
    // frame_buf_ptr = (uint8_t*)test_images[img_idx];
    // Serial.printf("[Test %d/%d] true label: %s\n", img_idx + 1, test_image_count, test_image_labels[img_idx]);

    // Step 3: Set up the Edge Impulse signal descriptor — tells the SDK how
    // many pixels to expect and which function to call to read them
    signal_t signal;
    signal.total_length = EI_CLASSIFIER_INPUT_WIDTH * EI_CLASSIFIER_INPUT_HEIGHT;
    signal.get_data     = &get_signal_data;

    // Step 4: Run inference
    // esp_task_wdt_reset() feeds the watchdog timer just before the ~4.5s
    // float32 inference call so the device doesn't reset mid-inference.
    ei_impulse_result_t result;

    run_classifier_init();
    esp_task_wdt_reset();
    EI_IMPULSE_ERROR ei_err = run_classifier(&signal, &result, false);

    if (ei_err != EI_IMPULSE_OK) {
        Serial.printf("Classifier error: %d\n", ei_err);
        esp_camera_fb_return(fb);  // still release the buffer on the error path
        return;
    }

    // Step 5: Extract scores for each class from the result
    float hazard_score  = 0;
    float ambient_score = 0;
    for (size_t i = 0; i < EI_CLASSIFIER_LABEL_COUNT; i++) {
        const char* label = result.classification[i].label;
        float  value = result.classification[i].value;

        if (strcmp(label, "hazard_detected") == 0) hazard_score  = value;
        if (strcmp(label, "ambient_noise")  == 0) ambient_score = value;
    }

    // Step 6: Trigger the LED if the hazard confidence exceeds 60%
    bool hazard_detected = hazard_score > 0.6f;
    digitalWrite(LED_PIN, hazard_detected ? HIGH : LOW);

    // Step 7: (debug) Stream the exact frame the classifier just saw over serial,
    // tagged with the decision and both scores. scripts/capture_classified_frames.py
    // reads this and saves it as a PNG so you can inspect what produced each result.
    // Done before esp_camera_fb_return so fb->buf is still valid.
#if DUMP_FRAMES
    Serial.printf("FRAME_START:%u:%s:%.4f:%.4f\n",
        (unsigned)fb->len,
        hazard_detected ? "hazard" : "clear",
        hazard_score, ambient_score);
    Serial.write(fb->buf, fb->len);
    Serial.println();
#endif

    // Release the camera frame buffer now that we're done with the pixels
    esp_camera_fb_return(fb);

    // Step 8: Send a Telegram alert (disabled — uncomment with WiFi to re-enable)
    // if (millis() - last_alert_ms > ALERT_COOLDOWN_MS) {
    //     sendTelegramAlert(hazard_score);
    //     last_alert_ms = millis();
    // }

    // Step 9: Print result to serial monitor
    Serial.printf("[Inference] hazard=%.8f  ambient=%.8f  → %s\n",
        hazard_score, ambient_score,
        hazard_detected ? "HAZARD DETECTED" : "clear");
}
