#!/usr/bin/env python3
"""
Convert one or more dataset images to a C header file for firmware testing.
The firmware will cycle through each image and print the model's prediction.

Usage:
    python scripts/image_to_header.py path/to/img1.png path/to/img2.png ...
"""

import argparse
import os
import sys
from PIL import Image

IMG_W, IMG_H = 96, 96
OUT_HEADER = os.path.join(
    os.path.dirname(__file__),
    "../firmware/hazard_beacon/src/test_image.h"
)


def infer_label(path):
    for part in os.path.normpath(os.path.abspath(path)).split(os.sep):
        if part in ("hazard_present", "ambient_noise"):
            return part
    return "unknown"


def image_to_bytes(path):
    img = Image.open(path).convert("L").resize((IMG_W, IMG_H))
    return list(img.tobytes())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("images", nargs="+", help="Paths to source images")
    args = parser.parse_args()

    entries = []
    for path in args.images:
        if not os.path.isfile(path):
            print(f"ERROR: file not found: {path}")
            sys.exit(1)
        entries.append((path, infer_label(path), image_to_bytes(path)))

    n = len(entries)
    lines = [
        "// Auto-generated by scripts/image_to_header.py — do not edit by hand",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const int test_image_count = {n};",
        "",
        f"static const char* test_image_labels[{n}] = {{",
    ]
    for _, label, _ in entries:
        lines.append(f'    "{label}",')
    lines.append("};")
    lines.append("")

    lines.append(f"static const uint8_t test_images[{n}][{IMG_W * IMG_H}] = {{")
    for path, label, pixels in entries:
        lines.append(f"    // {os.path.basename(path)}  ({label})")
        lines.append("    {")
        for row in range(0, len(pixels), 16):
            chunk = pixels[row : row + 16]
            lines.append("        " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
        lines.append("    },")
    lines += ["};", ""]

    with open(OUT_HEADER, "w") as f:
        f.write("\n".join(lines))

    print(f"Written {n} images → {OUT_HEADER}")
    for i, (path, label, _) in enumerate(entries):
        print(f"  [{i+1}] {label:15}  {os.path.basename(path)}")


if __name__ == "__main__":
    main()
